routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AntrianController;
use App\Http\Controllers\BayiController;
use App\Http\Controllers\BidanController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KbController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\LaporanbayiController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\LivechatController;
use App\Http\Controllers\MedisController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PantaubayiController;
use App\Http\Controllers\PantaubumilController;
use App\Http\Controllers\PantaukbController;
use App\Http\Controllers\PasienController;
use App\Http\Controllers\PersalinanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\PosyanduController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use App\Models\Layanan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LandingController::class, 'index']);

Route::get('/login', [UserController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [UserController::class, 'login'])->name('login');

Route::get('/logout', [UserController::class, 'logout'])->name('logout');

Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store'])->name('register');

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin')->middleware('auth');

    Route::resource('antrian', AntrianController::class)->middleware('auth');

    Route::resource('bumil', BumilController::class)->middleware('auth');
    Route::resource('pantaubumil', PantaubumilController::class)->middleware('auth');

    Route::resource('kb', KbController::class)->middleware('auth');
    Route::resource('pantaukb', PantaukbController::class)->middleware('auth');

    Route::resource('bidan', BidanController::class)->middleware('auth');

    Route::resource('pasien', PasienController::class)->middleware('auth');

    Route::resource('petugas', PetugasController::class)->middleware('auth');

    Route::resource('bayi', BayiController::class)->middleware('auth');
    Route::resource('pantaubayi', PantaubayiController::class)->middleware('auth');
    Route::resource('laporanbayi', LaporanbayiController::class)->middleware('auth');

    Route::resource('imunisasi', ImunisasiController::class)->middleware('auth');

    Route::resource('obat', ObatController::class)->middleware('auth');

    Route::resource('medis', MedisController::class)->middleware('auth');

    Route::resource('posyandu', PosyanduController::class)->middleware('auth');

    Route::resource('layanan', LayananController::class)->middleware('auth');

    Route::resource('persalinan', PersalinanController::class)->middleware('auth');

    Route::resource('konsultasi', KonsultasiController::class)->middleware('auth');
    
    Route::resource('user', AdminController::class)->middleware('auth');

    Route::resource('mitra', MitraController::class)->middleware('auth');

    Route::resource('blog', BlogController::class)->middleware('auth');
});

resources/views/home.blade.php
@extends('layouts.index')
@section('title', 'Home')

@section('content')
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
        </div>
      </div>
    </div>
  </div>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-3 col-6">
          <div class="small-box bg-secondary">
            <div class="inner">
              <h3>{{ $antrian }}</h3>
              <p>Antrian</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{ route('antrian.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
          @if (auth()->user()->role->role == 'superadmin')
          <div class="col-lg-3 col-6">
          <div class="small-box bg-primary">
            <div class="inner">
              <h3>{{ $posyandu }}</h3>
              <p>Posyandu</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{ route('posyandu.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
          @endif
        <div class="col-lg-3 col-6">
          <div class="small-box bg-info">
            <div class="inner">
              <h3>{{ $bidan }}</h3>
              <p>Bidan</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-add"></i>
            </div>
            <a href="{{ route('bidan.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-6">
          <div class="small-box bg-warning">
            <div class="inner">
              <h3>{{ $bumil }}</h3>
              <p>Ibu Hamil</p>
            </div>
            <div class="icon">
              <i class="ion ion-medkit"></i>
            </div>
            <a href="{{ route('imunisasi.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
        <div class="col-lg-3 col-6">
          <div class="small-box bg-success">
            <div class="inner">
              <h3>{{ $bayi }}</h3>
              <p>Bayi</p>
            </div>
            <div class="icon">
              <i class="ion ion-person-stalker"></i>
            </div>
            <a href="{{ route('bayi.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>


        <div class="col-lg-3 col-6">
          <div class="small-box bg-danger">
            <div class="inner">
              <h3>{{ $kb }}</h3>
              <p>KB</p>
            </div>
            <div class="icon">
              <i class="ion ion-pie-graph"></i>
            </div>
            <a href="{{ route('obat.index') }}" class="small-box-footer">Selengkapnya <i class="fas fa-arrow-circle-right"></i></a>
          </div>
        </div>
      </div>
    </div>
  </section>

@endsection