routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AntrianController;
use App\Http\Controllers\BayiController;
use App\Http\Controllers\BidanController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KbController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\LaporanbayiController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\LivechatController;
use App\Http\Controllers\MedisController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PantaubayiController;
use App\Http\Controllers\PantaubumilController;
use App\Http\Controllers\PantaukbController;
use App\Http\Controllers\PasienController;
use App\Http\Controllers\PersalinanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\PosyanduController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use App\Models\Layanan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LandingController::class, 'index']);

Route::get('/login', [UserController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [UserController::class, 'login'])->name('login');

Route::get('/logout', [UserController::class, 'logout'])->name('logout');

Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store'])->name('register');

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin')->middleware('auth');

    Route::resource('antrian', AntrianController::class)->middleware('auth');

    Route::resource('bumil', BumilController::class)->middleware('auth');
    Route::resource('pantaubumil', PantaubumilController::class)->middleware('auth');

    Route::resource('kb', KbController::class)->middleware('auth');
    Route::resource('pantaukb', PantaukbController::class)->middleware('auth');

    Route::resource('bidan', BidanController::class)->middleware('auth');

    Route::resource('pasien', PasienController::class)->middleware('auth');

    Route::resource('petugas', PetugasController::class)->middleware('auth');

    Route::resource('bayi', BayiController::class)->middleware('auth');
    Route::resource('pantaubayi', PantaubayiController::class)->middleware('auth');
    Route::resource('laporanbayi', LaporanbayiController::class)->middleware('auth');

    Route::resource('imunisasi', ImunisasiController::class)->middleware('auth');

    Route::resource('obat', ObatController::class)->middleware('auth');

    Route::resource('medis', MedisController::class)->middleware('auth');

    Route::resource('posyandu', PosyanduController::class)->middleware('auth');

    Route::resource('layanan', LayananController::class)->middleware('auth');

    Route::resource('persalinan', PersalinanController::class)->middleware('auth');

    Route::resource('konsultasi', KonsultasiController::class)->middleware('auth');
    
    Route::resource('user', AdminController::class)->middleware('auth');

    Route::resource('mitra', MitraController::class)->middleware('auth');

    Route::resource('blog', BlogController::class)->middleware('auth');
});

app/Models/Bumil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Bumil extends Model
{
    use HasFactory;

    protected $fillable = [
        'nama',
        'tmp_lahir',
        'tgl_lahir',
        'nik',
        'kk',
        'status',
        'alamat',
        'pekerjaan',
        'no_hp',
        'suami',
        'anak_ke',
        'bb',
        'tensi',
        'usia_hamil',
        'catatan_pemeriksaan',
        'posyandu_id'
    ];

    public function pantaubumil()
    {
        return $this->hasOne(Pantaubumil::class);
    }
}

app/Http/Controllers/BumilController.php
<?php

namespace App\Http\Controllers;

use App\Models\Bumil;
use App\Models\Pantaubumil;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BumilController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role->role == 'superadmin'){
            $data = Bumil::all();
        }else{
            $data = Bumil::all()->where('posyandu_id','==', Auth::user()->posyandu->id);
        }
        return view('bumil.index', compact(['data']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bumil.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $simpan = Bumil::create($request->all());
        if ($simpan) {
            $data = Bumil::all();
            return redirect()->route('bumil.index', compact('data'));
        }
        else {
            return view('bumil.create');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Bumil  $bumil
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Bumil::find($id);
        $pantau = Pantaubumil::where('bumil_id', $id)->get();
        // $date = date('Y:m:d H:i:s',strtotime($pantau[0]->created_at));
        // dd( $date );
        return view('bumil.show', compact(['data', 'pantau']));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Bumil  $bumil
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Bumil::where('id', $id)->first();
        return view('bumil.edit',compact(['data']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Bumil  $bumil
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = Bumil::where('id',$id)->first();
        $data->update($request->all());
        return redirect()->route('bumil.show', $data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Bumil  $bumil
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = Bumil::where('id', $id)->delete();
        if ($del) {
            $data = Bumil::all();
            return redirect()->route('bumil.index', compact('data'));
        }
    }
}

resources/views/bumil/buat.blade.php
@extends('layouts.index')
  @section('content')
    <h1>Pemeriksaan</h1>
  </section>
  @endsection

resources/views/bumil/create.blade.php
@extends('layouts.index')
  @section('content')
    <section class="content-header">
    </section>
      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card card-primary">
                <div class="card-header">
                  <h3 class="card-title">Tambah Data Ibu Hamil</h3>
                </div>
                <form method="POST" action="{{ route('bumil.store') }}">
                  @csrf
                    <div class="card-body">
                      <div class="row">
                        <div class="col-md-6">
                          <div class="form-group">
                            <label for="nama">Nama Lengkap</label>
                            <input type="text" name="nama" class="form-control" id="nama" placeholder="Nama Lengkap" required>
                          </div>
                          <div class="form-group">
                            <label for="tmp_lahir">Tempat Lahir</label>
                            <input type="text" name="tmp_lahir" class="form-control" id="tmp_lahir" placeholder="Tempat Lahir" required>
                          </div>
                          <div class="form-group">
                            <label for="tgl_lahir">Tanggal Lahir</label>
                            <input type="date" name="tgl_lahir" class="form-control" id="tgl_lahir" placeholder="yy/mm/dd" required>
                          </div>
                          <div class="form-group">
                            <label for="nik">NIK</label>
                            <input type="text" name="nik" class="form-control" id="nik" placeholder="NIK" required>
                          </div>
                          <div class="form-group">
                            <label for="kk">No. KK</label>
                            <input type="text" name="kk" class="form-control" id="kk" placeholder="No. KK" required>
                          </div>
                          <div class="form-group">
                            <label>Status Warga</label>
                            <select id="status" name="status" class="form-control">
                              <option>Pilih...</option>
                              <option>Domisili Tetap</option>
                              <option>Domisili Numpang</option>
                              <option>Lainnya</option>
                            </select>
                          </div>
                          <div class="form-group">
                            <label for="alamat">Alamat</label>
                            <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat" required>
                          </div>
                          <div class="form-group">
                            <label for="pekerjaan">Pekerjaan</label>
                            <input type="text" name="pekerjaan" class="form-control" id="pekerjaan" placeholder="Pekerjaan" required>
                          </div>
                        </div>
                        <div class="col-md-6">
                          <div class="form-group">
                            <label>Nomor Telepon</label>
                            <div class="input-group">
                              <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-phone"></i></span>
                              </div>
                              <input type="text" name="no_hp" id="no_hp" class="form-control" placeholder="+62" data-mask>
                            </div>
                          </div>
                          <div class="form-group">
                            <label for="suami">Nama Suami</label>
                            <input type="text" name="suami" class="form-control" id="suami" placeholder="Nama Suami" required>
                          </div>
                            <input name="posyandu_id" value="{{auth()->user()->posyandu->id}}" hidden>
                          <div class="form-group">
                            <label for="anak_ke">Mengandung Anak Ke-</label>
                            <input type="number" name="anak_ke" class="form-control" id="anak_ke" placeholder="Mengandung Anak Ke" required>
                          </div>
                          <div class="form-group">
                            <label for="bb">Berat Badan</label>
                            <input type="number" name="bb" class="form-control" id="bb" placeholder="Berat Badan" required>
                          </div>
                          <div class="form-group">
                            <label for="tensi">Tensi Darah</label>
                            <input type="number" name="tensi" class="form-control" id="tensi" placeholder="Tensi Darah" required>
                          </div>
                          <div class="form-group">
                            <label for="usia_hamil">Usia Kehamilan</label>
                            <input type="number" name="usia_hamil" class="form-control" id="usia_hamil" placeholder="Usia Kehamilan" required>
                          </div>
                          <div class="form-group">
                            <label>Catatan Pemeriksaan</label>
                            <textarea class="form-control" rows="2" required name="catatan_pemeriksaan" id="catatan_pemeriksaan" placeholder="......"></textarea>
                          </div>
                        </div>
                      </div>
                    </div>
                  <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
  @endsection

resources/views/bumil/edit.blade.php
@extends('layouts.index')

  @section('content')
        <section class="content-header">
            
          </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Edit Data Ibu Hamil</h3>
                        </div>
                        <form method="POST" action="{{ route('bumil.update', $data->id) }}">
                            @method('PATCH')
                            @csrf
                            <div class="card-body">
                              <div class="row">
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label for="nama">Nama Lengkap</label>
                                    <input type="text" name="nama" class="form-control" id="nama" placeholder="Nama Lengkap" value="{{ $data->nama }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="tmp_lahir">Tempat Lahir</label>
                                    <input type="text" name="tmp_lahir" class="form-control" id="tmp_lahir" placeholder="Tempat Lahir" value="{{ $data->tmp_lahir }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="tgl_lahir">Tanggal Lahir</label>
                                    <input type="date" name="tgl_lahir" class="form-control" id="tgl_lahir" placeholder="yy/mm/dd" value="{{ $data->tgl_lahir }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="nik">NIK</label>
                                    <input type="text" name="nik" class="form-control" id="nik" placeholder="NIK" value="{{ $data->nik }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="kk">No. KK</label>
                                    <input type="text" name="kk" class="form-control" id="kk" placeholder="No. KK" value="{{ $data->kk }}">
                                  </div>
                                  <div class="form-group">
                                    <label>Status Warga</label>
                                    <select id="status" name="status" value="satus" class="form-control">
                                      <option>Pilih...</option>
                                      <option>Domisili Tetap</option>
                                      <option>Domisili Numpang</option>
                                      <option>Lainnya</option>
                                    </select>
                                  </div>
                                  <div class="form-group">
                                    <label for="alamat">Alamat</label>
                                    <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat" value="{{ $data->alamat }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="pekerjaan">Pekerjaan</label>
                                    <input type="text" name="pekerjaan" class="form-control" id="pekerjaan" placeholder="Pekerjaan" value="{{ $data->pekerjaan }}" required>
                                  </div>
                                </div>
                                <div class="col-md-6">
                                  <div class="form-group">
                                    <label>Nomor Telepon</label>
                                    <div class="input-group">
                                      <div class="input-group-prepend">
                                        <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                      </div>
                                      <input type="text" name="no_hp" id="no_hp" value="{{ $data->no_hp }}" class="form-control" placeholder="+62" data-mask>
                                    </div>
                                  </div>
                                  <div class="form-group">
                                    <label for="suami">Nama Suami</label>
                                    <input type="text" name="suami" class="form-control" id="suami" placeholder="Nama Suami" value="{{ $data->suami }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="anak_ke">Mengandung Anak Ke-</label>
                                    <input type="number" name="anak_ke" class="form-control" id="anak_ke" placeholder="Mengandung Anak Ke" value="{{ $data->anak_ke }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="bb">Berat Badan</label>
                                    <input type="number" name="bb" class="form-control" id="bb" placeholder="Berat Badan" value="{{ $data->bb }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="tensi">Tensi Darah</label>
                                    <input type="number" name="tensi" class="form-control" id="tensi" placeholder="Tensi Darah" value="{{ $data->tensi }}">
                                  </div>
                                  <div class="form-group">
                                    <label for="usia_hamil">Usia Kehamilan</label>
                                    <input type="number" name="usia_hamil" class="form-control" id="usia_hamil" placeholder="Usia Kehamilan" value="{{ $data->usia_hamil }}">
                                  </div>
                                  <div class="form-group">
                                    <label>Catatan Pemeriksaan</label>
                                    <textarea class="form-control" name="catatan_pemeriksaan" id="catatan_pemeriksaan"  rows="3">{{ $data->catatan_pemeriksaan }}</textarea>
                                  </div>
                                </div>
                          </div>
                    </div>
                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Update</button>
                        <button type="button" onclick="window.history.back()" class="btn btn-danger">Batal</button>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </section>
  @endsection

resources/views/bumil/show.blade.php
@extends('layouts.index')
  @section('content')

          {{-- <section class="content">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">Tabel Ibu Hamil</h3>
                    </div>

                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-6">
                            <div class="form-group">
                              <label for="nama">Nama Lengkap</label>
                              <input type="text" name="nama" class="form-control" id="nama" placeholder="Nama Lengkap" value="{{ $data->nama }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="tmp_lahir">Tempat Lahir</label>
                              <input type="text" name="tmp_lahir" class="form-control" id="tmp_lahir" placeholder="Tempat Lahir" value="{{ $data->tmp_lahir }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="tgl_lahir">Tanggal Lahir</label>
                              <input type="date" name="tgl_lahir" class="form-control" id="tgl_lahir" placeholder="yy/mm/dd" value="{{ $data->tgl_lahir }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="nik">NIK</label>
                              <input type="text" name="nik" class="form-control" id="nik" placeholder="NIK" value="{{ $data->nik }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="kk">No. KK</label>
                              <input type="text" name="kk" class="form-control" id="kk" placeholder="No. KK" value="{{ $data->kk }}" disabled>
                            </div>
                            <div class="form-group">
                              <label>Status Warga</label>
                              <select id="status" name="status" value="{{ $data->status }}" class="form-control">
                                <option>Pilih...</option>
                                <option>Domisili Tetap</option>
                                <option>Domisili Numpang</option>
                                <option>Lainnya</option>
                              </select>
                            </div>
                            <div class="form-group">
                              <label for="alamat">Alamat</label>
                              <input type="text" name="alamat" class="form-control" id="alamat" placeholder="Alamat" value="{{ $data->alamat }}" disabled>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                              <label>Nomor Telepon</label>
                              <div class="input-group">
                                <div class="input-group-prepend">
                                  <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                </div>
                                <input type="text" name="no_hp" id="no_hp" value="{{ $data->no_hp }}" class="form-control" placeholder="+62" data-mask disabled>
                              </div>
                            </div>
                            <div class="form-group">
                              <label for="suami">Nama Suami</label>
                              <input type="text" name="suami" class="form-control" id="suami" placeholder="Nama Suami" value="{{ $data->suami }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="anak_ke">Mengandung Anak Ke-</label>
                              <input type="number" name="anak_ke" class="form-control" id="anak_ke" placeholder="Mengandung Anak Ke" value="{{ $data->anak_ke }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="bb">Berat Badan</label>
                              <input type="number" name="bb" class="form-control" id="bb" placeholder="Berat Badan" value="{{ $data->bb }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="tensi">Tensi Darah</label>
                              <input type="number" name="tensi" class="form-control" id="tensi" placeholder="Tensi Darah" value="{{ $data->tensi }}" disabled>
                            </div>
                            <div class="form-group">
                              <label for="usia_hamil">Usia Kehamilan</label>
                              <input type="number" name="usia_hamil" class="form-control" id="usia_hamil" placeholder="Usia Kehamilan" value="{{ $data->usia_hamil }}" disabled>
                            </div>
                            <div class="form-group">
                              <label>Catatan Pemeriksaan</label>
                              <textarea class="form-control" name="catatan_pemeriksaan" id="catatan_pemeriksaan"  rows="3" disabled>{{ $data->catatan_pemeriksaan }}</textarea >
                            </div>
                          </div>
                      </div>
                      </div>
                      <div class="card-footer">
                        <button type="button" onclick="window.history.back()" class="btn btn-warning">Kembali</button>
                      </div>
                  </div>
                </div>
              </div>
            </div>
          </section> --}}
        <section class="content-header">
          <div class="invoice p-4 mb-3">
              <!-- title row -->
              <div class="card-header">
                  <h2 class="card-title mt-2"><strong>Detail Ibu Hamil</strong></h2>
                    <div class="card-tools">
                        @if (auth()->user()->role->role != 'User')
                        <a href="{{route('pantaubumil.show', $data->id)}}">
                            <button type="button" class="btn btn-success" title="Tambah">
                                <i class="fas solid fa-plus mr-2" ></i>Pemeriksaan
                            </button>
                        </a>
                        @endif
                        <button type="button" onclick="window.history.back()" class="btn btn-warning" title="Batal">
                          <i class="fas solid fa-arrow-left mr-2"></i>Batal
                        </button>
                    </div>
              </div>

              <div class="row ">
                <div class="col-sm-6 ">
                  <table class="table table-borderless">
                    <tr>
                      <td><strong>Nama Lengkap</strong></td>
                      <td>:</td>
                      <td><strong>{{ $data->nama }}</strong></td>
                    </tr>
                    <tr>
                      <td><strong>Tempat, Tgl Lahir</strong></td>
                      <td>:</td>
                      <td>{{ $data->tgl_lahir }}</td>
                    </tr>
                    <tr>
                      <td><strong>NIK</strong></td>
                      <td>:</td>
                      <td>{{ $data->nik }}</td>
                    </tr>
                  </table>
                </div>
                <div class="col-sm-6 ">
                  <table class="table table-borderless">
                    <tr>
                      <td><strong>Mengandung Anak Ke</strong></td>
                      <td>:</td>
                      <td>{{ $data->anak_ke }}</td>
                    </tr>
                    <tr>
                      <td><strong>Nama Suami</strong></td>
                      <td>:</td>
                      <td>{{ $data->suami }}</td>
                    </tr>
                    <tr>
                      <td><strong>No. KK</strong></td>
                      <td>:</td>
                      <td>{{ $data->kk }}</td>
                    </tr>
                  </table>
                </div>
              </div>

              <!-- Table row -->
              <div class="row">
                <div class="col-12 table-responsive">
                  <table class="table table-striped border-0">
                    <thead>
                      <tr>
                        <th>#</th>
                        <th>TANGGAL PERSIKSA</th>
                        <th>TENSI</th>
                        <th>BERAT</th>
                        <th>USIA</th>
                        <th>CATATAN</th>
                        <th style="widows: 5%">AKSI</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        @foreach ($pantau as $item)
                          <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ date('D, d M Y H:i:s',strtotime($item->created_at)) }}</td>
                            <td>{{ $item->tensi }}</td>
                            <td>{{ $item->bb }}</td>
                            <td>{{ $item->usia }}</td>
                            <td>{{ $item->ket_pemeriksaan }}</td>
                              <td class="project-actions text-center">
                                @if (auth()->user()->role->role != 'User')
                                <div class="row justify-content-center align-item-center">
                                  
                                    <form method="post" action="{{ route('pantaubumil.destroy', $item->id) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button class="btn btn-danger btn-sm m-1" href="#" title="Hapus">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </form>
                                </div>
                                @endif
                              </td>
                          </tr>
                        @endforeach
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
              </div>
            </div>
          </section>
  @endsection