routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AntrianController;
use App\Http\Controllers\BayiController;
use App\Http\Controllers\BidanController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BumilController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImunisasiController;
use App\Http\Controllers\KbController;
use App\Http\Controllers\KonsultasiController;
use App\Http\Controllers\LandingController;
use App\Http\Controllers\LaporanbayiController;
use App\Http\Controllers\LayananController;
use App\Http\Controllers\LivechatController;
use App\Http\Controllers\MedisController;
use App\Http\Controllers\MitraController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\PantaubayiController;
use App\Http\Controllers\PantaubumilController;
use App\Http\Controllers\PantaukbController;
use App\Http\Controllers\PasienController;
use App\Http\Controllers\PersalinanController;
use App\Http\Controllers\PetugasController;
use App\Http\Controllers\PosyanduController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\UserController;
use App\Models\Layanan;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LandingController::class, 'index']);

Route::get('/login', [UserController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [UserController::class, 'login'])->name('login');

Route::get('/logout', [UserController::class, 'logout'])->name('logout');

Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store'])->name('register');

Route::group(['prefix' => 'admin'], function () {
    Route::get('/', [HomeController::class, 'index'])->name('admin')->middleware('auth');

    Route::resource('antrian', AntrianController::class)->middleware('auth');

    Route::resource('bumil', BumilController::class)->middleware('auth');
    Route::resource('pantaubumil', PantaubumilController::class)->middleware('auth');

    Route::resource('kb', KbController::class)->middleware('auth');
    Route::resource('pantaukb', PantaukbController::class)->middleware('auth');

    Route::resource('bidan', BidanController::class)->middleware('auth');

    Route::resource('pasien', PasienController::class)->middleware('auth');

    Route::resource('petugas', PetugasController::class)->middleware('auth');

    Route::resource('bayi', BayiController::class)->middleware('auth');
    Route::resource('pantaubayi', PantaubayiController::class)->middleware('auth');
    Route::resource('laporanbayi', LaporanbayiController::class)->middleware('auth');

    Route::resource('imunisasi', ImunisasiController::class)->middleware('auth');

    Route::resource('obat', ObatController::class)->middleware('auth');

    Route::resource('medis', MedisController::class)->middleware('auth');

    Route::resource('posyandu', PosyanduController::class)->middleware('auth');

    Route::resource('layanan', LayananController::class)->middleware('auth');

    Route::resource('persalinan', PersalinanController::class)->middleware('auth');

    Route::resource('konsultasi', KonsultasiController::class)->middleware('auth');
    
    Route::resource('user', AdminController::class)->middleware('auth');

    Route::resource('mitra', MitraController::class)->middleware('auth');

    Route::resource('blog', BlogController::class)->middleware('auth');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable =
    [
        'name',
        'username',
        'email',
        'password',
        'posyandu_id'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->hasOne(Role::class, );
    }

    public function konsultasi()
    {
        return $this->hasOne(Konsultasi::class);
    }
    public function posyandu(){
        return $this->belongsTo(Posyandu::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Posyandu;
use App\Models\User;
use GuzzleHttp\Psr7\Response;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->pralogin){
//            dd($request->all());
            return view('login.login', [
                'title' => 'Login'
            ]);
        }else{
            $posyandu = Posyandu::all();
            $title = 'login';
            return view('userlogin.userlogin', compact(['posyandu','title']));
        }

    }

    public function login(Request $request){
        $email = User::where('email', $request->email)->first();
//         dd($email->em);
        if ($email){
            if ($request->pralogin == $email->posyandu->nama){
                if (Hash::check($request->password, $email->password)){
                    if(Auth::attempt(['email' => $request->email, 'password' => $request->password], remember:1)){
                        $request->session()->regenerate();
                        return redirect()->route('admin');
                    }
                }
            }else if($email->role->role == 'superadmin'){
                if (Hash::check($request->password, $email->password)){
                    if(Auth::attempt(['email' => $request->email, 'password' => $request->password], remember:1)){
                        $request->session()->regenerate();
                        return redirect()->route('admin');
                    }
                }
            }
        }
        return redirect()->route('login');
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request>session()->invalidate();
        $request>session()->regenerateToken();
        return redirect()->route('login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/user/create.blade.php
@extends('layouts.index')

  @section('content')
        <section class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Tabel User</h1>
                </div>
              </div>
            </div>
          </section>
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                <div class="col-md-12">
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Tambah Data User</h3>
                    </div>
                    <form method="POST" action="{{ route('user.store') }}">
                        @csrf
                        <div class="card-body">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Masukkan nama">
                        </div>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="username" name="username" class="form-control" id="username" placeholder="username">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control" id="email" placeholder="email">
                        </div>
                        <div class="form-group">
                            <label>Level</label>
                            <select id="role" name="role" class="form-control">
                              <option>Pilih...</option>
                              <option>Admin</option>
                              <option>Bidan</option>
                              <option>Kader</option>
                              <option>User</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control" id="password" placeholder="***">
                        </div>
                        </div>
{{--                        </div>--}}
                        <div class="card-footer">
                        <button type="submit" class="btn btn-primary">Simpan</button>
                        </div>
                    </form>
                    </div>
                </div>
                </div>
            </div>
        </section>
  @endsection

resources/views/user/edit.blade.php
@extends('layouts.index')

  @section('content')
        <section class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Tabel User</h1>
                </div>
              </div>
            </div>
          </section>

        <section class="content">
            <div class="container-fluid">
                <div class="row">
                <div class="col-md-8">
                    <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Data user</h3>
                    </div>
                    <form method="POST" action="{{ route('user.update', $data->id) }}">
                        @method('PATCH')
                        @csrf
                        <div class="card-body">
                        <div class="form-group">
                            <label for="name">Nama</label>
                            <input type="name" name="name" value="{{ $data->name }}" class="form-control" id="name">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" value="{{ $data->email }}" class="form-control" id="email">
                        </div>
                        <div class="form-group">
                            <label>Level</label>
                            <select id="role" name="role" class="form-control">
                              <option>Pilih...</option>
                              <option>Admin</option>
                              <option>Bidan</option>
                              <option>Kader</option>
                              <option>User</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control" id="password">
                        </div>
                        </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Update</button>
                            <button type="button" onclick="window.history.back()" class="btn btn-danger">Batal</button>
                        </div>
                    </form>
                    </div>
                </div>
                </div>
            </div>
        </section>
  @endsection

resources/views/user/index.blade.php
@extends('layouts.index')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Data User</h1>
                </div>
            </div>
        </div>
    </section>
    <section class="content">
        <div class="card">
                <div class="card-header">
                    <h3 class="card-title mt-2">Daftar User</h3>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                        <a href="{{route('user.create')}}">
                            <button type="button" class="btn btn-default" title="Tambah">
                            <i class="fas fa-plus-circle"></i>
                            </button>
                        </a>
                    </div>
                </div>
                    <!-- /.card-header -->
                <div class="card-body">
                    <table class="table table-bordered">
                    <thead>
                        <tr class="text-center">
                            <th style="width: 1%">#</th>
                            <th style="width: 30%">Nama</th>
                            <th style="width: 30%">Email</th>
                            <th style="width: 5%">Level</th>
                            <th style="width: 12%">Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $item)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $item->name }}</td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->role->role }}</td>
                                <td class="project-actions text-center">
                                    <div class="row justify-content-center align-item-center">
                                        <a class="btn btn-primary btn-sm m-1" href="{{ route('user.show', $item->id) }}">
                                            <i class="fas fa-eye"></i>
                                        </a>
                                        <a class="btn btn-warning btn-sm m-1" href="{{ route('user.edit', $item->id) }}">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        <form method="post" action="{{ route('user.destroy', $item->id) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger btn-sm m-1" href="#" >
                                                <i class="fas fa-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                    </table>
                </div>
            <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                <li class="page-item"><a class="page-link" href="#">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">&raquo;</a></li>
                </ul>
            </div>
        </div>
    </section>
@endsection

resources/views/user/show.blade.php
@extends('layouts.index')

  @section('content')
        <section class="content-header">
            <div class="container-fluid">
              <div class="row mb-2">
                <div class="col-sm-6">
                  <h1>Profil User</h1>
                </div>
              </div>
            </div>
          </section>
          <section class="content">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-12">
                  <div class="card card-primary">
                    <div class="card-header">
                      <h3 class="card-title">Profil User</h3>
                    </div>
                      <div class="card-body">
                        <div class="form-group">
                          <label for="name">Nama</label>
                          <input type="text" name="name" value="{{ $data->name }}" class="form-control" id="name" disabled>
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input type="email" name="email" value="{{ $data->email }}" class="form-control" id="email" disabled>
                        </div>
                        <div class="form-group">
                            <label for="role">Level</label>
                            <input type="text" name="role" class="form-control" id="role" disabled>
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control" id="password" disabled>
                        </div>
                      <div class="card-footer">
                        <button type="button" onclick="window.history.back()" class="btn btn-warning">Kembali</button>
                      </div>                    
                  </div>
                </div>
              </div>
            </div>
          </section>
  @endsection